### PR TITLE
Remove bad words

### PR DESCRIPTION
**Pull request by nicwaller**
## What

Remove "bad" words from the dictionary.

1. Download [bad-words.txt](https://www.cs.cmu.edu/~biglou/resources/bad-words.txt)
2. Trim bad-words.txt to only contain words already in our dictionary (for easier review)
3. Remove not-so-bad words from bad-words.txt (based on PR discussion)
4. Apply bad-words.txt to dictionary.js. _(Pro tip: this is easiest when dictionary.js has one word per line.)_

## Why

This is a [suggested improvement](https://github.com/canadianveggie/spellie/issues/45).

Fixes canadianveggie/spellie#45

### CODE REVIEW

**Comment by JimFung** [comment]
Some of these words should definitely be removed but also some of these words would be fun for a kid...like `butt`

**Comment by wachunga** [comment]
Thanks, @nicwaller!
I think removing "weapon" and some others may be too aggressive. I'll leave it to @canadianveggie to review because I know he has feelings on the topic.

**Comment by nicwaller** [comment]
I made a first pass at identifying words that should maybe remain in the dictionary:

<details>
<summary>Tolerable Words</summary>
anus
babe
barf
bast
blow
boob
boom
burn
butt
chin
dago
dead
died
dies
dike
dive
doom
dumb
dyke
fart
fear
fire
fore
hobo
hole
honk
hook
horn
itch
jade
jugs
kill
laid
lies
nook
nude
oral
piss
poop
puke
rump
scum
sick
snot
suck
teat
adult
angry
balls
beast
bible
black
blind
bombs
color
crabs
crack
crash
crime
death
demon
devil
dirty
drunk
enemy
erect
fairy
faith
feces
fight
fraud
girls
gross
husky
hymen
idiot
jesus
joint
kills
knife
loser
moles
naked
nasty
negro
penis
pubic
queer
rabbi
screw
shoot
slant
slave
slime
smack
spank
taboo
trots
urine
vomit
vulva
addict
areola
attack
babies
beaver
bigger
blacks
breast
buried
cancer
church
creamy
crimes
crotch
desire
escort
ethnic
faeces
failed
farted
firing
flange
fungus
german
harder
hijack
killed
killer
liquor
lotion
murder
nipple
period
pistol
racial
rectum
reject
rigger
robber
snatch
sniper
soviet
stroke
stupid
tampon
terror
toilet
tongue
trojan
uterus
vagina
virgin
weapon
whites
yankee
</details>

And on the flip side, that gives us a list of _worse words_.

<details>
<summary>Worse Words</summary>
anal
arse
bomb
bong
chav
cigs
clit
cock
coon
crap
cunt
damn
dick
dink
dong
dope
drug
fuck
geez
gook
gypo
hebe
hell
hoes
homo
hore
hork
jeez
jism
jizz
kike
kink
lezz
limy
mams
meth
milf
mofo
muff
munt
nazi
nuke
orgy
peck
perv
pimp
pixy
poon
porn
pros
pube
puss
quim
rape
scag
scat
sexy
shag
shat
shit
slut
smut
spic
spik
spit
tang
tits
turd
twat
wank
whit
whiz
whop
wuss
abuse
asses
bitch
bogan
boner
boobs
booby
boody
boong
booty
chink
chode
cocky
cooly
darky
dildo
enema
fagot
fatso
felch
fubar
fucks
fugly
ginzo
goyim
gyppo
gyppy
harem
honky
horny
hoser
hussy
jiggy
jihad
kafir
kinky
kraut
lesbo
limey
lynch
mafia
moron
niger
nymph
pansy
piker
pikey
pixie
pommy
porno
prick
pussy
randy
raped
raper
roach
sadis
semen
sexed
shite
shits
sissy
skank
slopy
sluts
sodom
sooty
sperm
spick
spunk
squaw
teste
titty
tramp
twink
whore
willy
biatch
bitchy
bohunk
boonga
bugger
chinky
coitus
commie
condom
coolie
crappy
cummer
dammit
darkie
diddle
doodoo
faggot
fetish
fondle
fucked
fucker
geezer
gringo
gummer
gyppie
heroin
herpes
honkey
hooker
hummer
incest
jigger
kaffir
libido
licker
looser
molest
nigger
niggle
nookie
nooner
nudger
orgasm
orgies
pecker
penile
pimped
pissed
pisser
pisses
polack
pommie
pooper
racist
rapist
reefer
retard
ribbed
sexing
sexpot
sexual
shited
shitty
skanky
slutty
sodomy
spunky
stiffy
sucker
tantra
tinkle
tittie
tosser
tranny
turnon
wanker
weenie
weewee
whitey
wigger
willie
</details>

**Comment by canadianveggie** [comment]
That list is way too aggressive. I definitely lead toward leaving more words in.

BLOW, BEAVER, CANCER, CHURCH, FART, and FAIRY should not be removed. I don't see any justification there.
I think we should leave words that are sometimes derogatory or vulgar, but have meanings that are perfectly fine (PRICK, LOSER, LICKER, RIBBED, PANSY).
I don't know how KAFFIR ended up on that list. I always thought that a was a type of lime, but I must be missing some prerogative. 
Medical terms like CONDOM, FECES, PENIS, VAGINA, and SPERM should be left in.

I'm definitely fine getting rid of the F word and other swears.
Words who's real meaning is derogative (GRINGO, GYPPO, FATSO) or vulgar (SHITE, ) should be removed.

Harder to decide what to do with a word like BITCH, RAPE, SLUTTY, JIHAD, PORN, and PUBE. I think I would lean toward leaving them in.

I think I'm going to run all of these through the dictionary and any word who's only meaning is derogative or vulgar is going to be removed. Does that sound like a good dividing line?

**Comment by nicwaller** [comment]
> Harder to decide what to do with a word like BITCH, RAPE, SLUTTY, JIHAD, PORN, and PUBE. I think I would lean toward leaving them in.

Part of my test was "How would a 4th grade teacher feel if they were playing Spellie with their class and this word popped up on the big screen?" For that reason I erred on the side of removing those words. But ultimately, not my call.

**Comment by nicwaller** [comment]
I've updated this PR substantially, taking most of @canadianveggie feedback into consideration.

This time I included the "bad-words" list as part of the PR. Changes to the bad-words list are organized into logical commits to make for easier reviewing.

**List of "bad" words that are okay for children:**
https://github.com/canadianveggie/spellie/pull/52/files/550bd97c348a1998b0cad397adda0fc9e161fae4..8fc5bfb73e1a74c55a57b80f212a75ae10b075b3

**List of removed words:**
https://github.com/canadianveggie/spellie/blob/999126eb4b625e2ffd0b81434bd23b8d1f3103bc/public/bad-words.txt

**Review by canadianveggie — CHANGES_REQUESTED** [review]
I suggest we add back in:
anal
babe
barf
boob
boobs
booty
damn 
enema
fetish
fondle
hell
horny
hoser
idiot
incest
jade
kink
kinky
moron
nasty
nymph
orgy
pimp
pimped
piss
pissed
pixie
porn
pros
randy
rape
raped
raper
rapist
robber
rump
sexual
sexy
slave
sooty
stupid
tinkle
tits
tramp
trots
turd

**Comment by canadianveggie** [comment]
I think we removed all the bad words this person was concerned about:
https://twitter.com/Xandria55595173/status/1495101687098339331
(Although I might suggest that COCK has plenty of valid uses)

**Comment by nicwaller** [comment]
> I think we removed all the bad words this person was concerned about:
> https://twitter.com/Xandria55595173/status/1495101687098339331
> (Although I might suggest that COCK has two non-vulgar definitions)

Almost.

```
nicwaller@serendipity public % grep -Ei '^"(cunt|cock|fuck|slut|clit|shit)' dictionary.js
"CLITS",
"COCKS",
"CUNTS",
"CLITIC",
"COCKED",
"COCKER",
"COCKET",
"COCKLE",
"COCKSY",
"COCKUP",
"FUCKUP",
"SHITES",
"SHITTY",
"SHITZU",
"SLUTCH",
```

**Comment by canadianveggie** [comment]
From that list, let's keep:
CLITIC
COCKED
COCKER (like the dog)
COCKLE
SHITZU
SLUTCH

and remove the rest.

**CLITIC**
>an unstressed word that normally occurs only in combination with another word, for example 'm in I'm.

**Comment by canadianveggie** [comment]
> > Harder to decide what to do with a word like BITCH, RAPE, SLUTTY, JIHAD, PORN, and PUBE. I think I would lean toward leaving them in.
> 
> Part of my test was "How would a 4th grade teacher feel if they were playing Spellie with their class and this word popped up on the big screen in front of the whole class?" For that reason I erred on the side of removing those words. But ultimately, not my call.

That's a good point. But the spell checker is optional right now, and even if we did hard enforce it, nothing would stop you from typing it in (before it was rejected). Before you press the enter key, the line is basically a text box. You can type any 4-6 characters you want.

**Comment by nicwaller** [comment]
Okay, all done (I think).

I left the dictionary in the original format because I don't like combining formatting changes and content changes in the same PR. But I really think the dictionary should be in word-per-line format, and plaintext would be _ideal_.

**Comment by canadianveggie** [comment]
> Okay, all done (I think).
> 
> I left the dictionary in the original format because I don't like combining formatting changes and content changes in the same PR. But I really think the dictionary should be in word-per-line format, and plaintext would be _ideal_.

You might be right. I did that to compress the file (it's 40 KB smaller without that whitespace), but gzipped requests might remove all that overhead anyway.

**Review by canadianveggie — APPROVED** [review]

**Pull request merged**
