### PR TITLE
Use twemoji instead of raw characters

### LINKED ISSUE #37: Cooler emojis
Have more fun with the emojis the user unlocks.

Consider:
- changing where emojis are displayed
- using a 3rd party emoji library (like https://twemoji.twitter.com/ or https://www.joypixels.com/)
- animated emojis

### PR DESCRIPTION
**Pull request by wachunga**
preview of what it would look like

columns:
- existing emoji character (status quo)
- twemoji image
- twemoji image with dark drop-shadow (to fix blue/grey ones)
- twemoji image with dark bg and light drop-shadow (to fix dark ones in notice message)

image

Closes #37 (though we may decide later to pay for JoyPixels)

### CODE REVIEW

**Comment by canadianveggie** [comment]
I like them. Although I was hoping for animated JoxPixel emojis (😁 ).
The drop shadows do a great job keeping them clear on blue, white (high contrast), or black backgrounds.

**Comment by wachunga** [comment]
Okay, I'll work on finalizing this PR. We can go with these ones (free and easy) and then look into joypixels later.

**Comment by wachunga** [comment]
updated screen:

image

**Comment by wachunga** [comment]
@canadianveggie ready for you review now

**Review by canadianveggie — APPROVED** [review]
Looks good to me. Tested in Safari and ensured the share emojis still works.

**Pull request merged**
