### PR TITLE
Improve tile layout

### PR DESCRIPTION
**Pull request by wachunga**
Tiles resize more nicely, except on older browsers like Safari <= 14. Please try it out.

I'd still like to tweak some font sizes etc before merging.

### CODE REVIEW

**Comment by canadianveggie** [comment]
It's still not quite expanding enough.
Screen Shot 2022-02-16 at 5 49 59 AM

**Comment by canadianveggie** [comment]
I get nice behaviour with these 2 change:
- remove the `aspect-ratio` on `guesses-row`
- add `flex-grow: 2` to `guesses-grid` - so that it takes up more space

Screen Shot 2022-02-16 at 5 53 53 AM

**Comment by wachunga** [comment]
> I get nice behaviour with these 2 change:
> 
> * remove the `aspect-ratio` on `guesses-row`
> * add `flex-grow: 2` to `guesses-grid` - so that it takes up more space

If you allow it to grow, the horizontal scaling doesn't work well. Sometimes the emojis are cut-off on some widths.

@canadianveggie pull and try again. It grows better now, I think.

image

**Comment by wachunga** [comment]
(that phone also has weird resolution - there isn't enough width for it to grow more and keep the circles correct)

**Review by canadianveggie — APPROVED** [review]
Much better.
LGTM

**Comment by canadianveggie** [comment]
I think we might be able to go even bigger on desktop, but this is perfect for now (to help teacher's casting to a projector)

**Pull request merged**
