### PR TITLE
Help and about page

### LINKED ISSUE #32: About/Help Page
Create a page with:
- rules
- why Spellie is different
- where to send feedback (https://twitter.com/SpellieGame or https://github.com/canadianveggie/spellie/issues)

### PR DESCRIPTION
**Pull request by deelan**
First crack at simple help and about pages.

Nothing fancy with the nav. Also kept the CSS simple by duplicating the game tile styles. Can certain try to reuse some of it, if you prefer.

Happy to change any of the text, of course.

Fixes #32

### CODE REVIEW

**Comment by canadianveggie** [comment]
Screen Shot 2022-02-19 at 5 06 47 PM
Screen Shot 2022-02-19 at 5 06 51 PM

**Comment by canadianveggie** [comment]
I duplicated all of this in #18. 😢 

I like your How to Play better.

Let's figure out how to consolidate them. Do you like having a separate About and Help? If we consolidate them, I think we can put the icon on the right and now have it interfere with the Back button.

**Comment by deelan** [comment]
I liked having them separate because it keeps the how to play concise, but minimizing extra screens is good too 🤷 

Anyway, I'll close this out!

**Comment by canadianveggie** [comment]
I'm going to grab big parts of this and move it into my PR. Thanks @deelan

**Pull request closed without merging**
